[package]
name = "filetree-traversing"
version = "0.1.2"
edition = "2021"
authors = ["Seal <will@kimbell.uk>"]
description = "A Rust library for working with file trees"
license = "MIT"
repository = "https://github.com/seal/filetree-traversing"
readme = "README.md"
keywords = ["file", "tree", "directory", "filesystem"]
categories = ["filesystem"]

[dependencies]
colored = "2.1.0"

[badges]
maintenance = { status = "actively-developed" }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]


[[bin]]
name = "filetree-traversing"
path = "src/main.rs"
